// ---------------------------
// This file was generated by Nango (v0.42.12)
// You can version this file
// ---------------------------

export interface Integration {
  [key: string]: any;
  id: string;
};

export interface LastSyncDate {
  lastSyncDate: string | null;
};

export interface Category {
  id: string;
  name: string;
  color: string;
  description: string | null;
  slug: string;
};
