// ---------------------------
// This file was generated by Nango (v0.48.1)
// You can version this file
// ---------------------------

export interface Integration {
  [key: string]: any;
  id: string;
};

export interface LastSyncDate {
  lastSyncDate: string | null;
};

export interface Category {
  id: string;
  name: string;
  color: string;
  description: string | null;
  slug: string;
};

export interface ContentToDb {
  sourcePage: string;
  targetDb: string;
};

export interface SuccessResponse {
  success: boolean;
};

export interface CreateLinearIssue {
  teamId: string;
  projectId: string;
  p1MilestoneId: string;
  p2MilestoneId: string;
  assigneeId?: string;
  priority?: number;
  parentId?: string;
  estimate?: number;
  dueDate?: string;
};

export interface CreatedTask {
  id: string;
  createdAt: string;
  updatedAt: string;
  dueDate: string;
  team: {  id: string;};
  title: string;
};
