// ---------------------------
// This file was generated by Nango (v0.42.12)
// You can version this file
// ---------------------------

export interface Integration {
  [key: string]: any;
  id: string;
};
